import { ArrowUpRight, Search } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect,useState } from "react";
import Navbar from "../components/Navbar";
import SectionTag from "../components/SectionTag";
import MarketplaceProductGrid from "../components/MarketplaceProductGrid";
import { LoadingState,ErrorState,FloatingChat } from "../components/States";
import { getProducts } from "../services/marketplaceApi";
function Column({title,products}){return <div className="product-column"><h3>{title}</h3>{products.map(p=><Link key={p.id} to={`/product/${p.id}`} className="small-product-card"><div><h4>{p.name}</h4><p>{p.emiText}</p></div><img src={p.image} alt={p.name}/></Link>)}</div>}
function Step({n,title,text}){return <article className="step-card"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>}
export default function Marketplace(){const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{getProducts().then(setProducts).catch(()=>setError("Please try again.")).finally(()=>setLoading(false))},[]);const group=x=>products.filter(p=>p.badge===x);return <div className="app"><Navbar/><main>
<section className="marketplace-hero"><div className="hero-pill"><span>✦ New</span><span>No-cost EMIs backed by mutual funds</span></div><h1>Shop today<em>Pay later</em>using <span>mutual funds.</span></h1><div className="hero-actions"><button className="button button-outline">Check Eligibility <ArrowUpRight size={18}/></button><a href="#products" className="button">Start Shopping <Search size={18}/></a></div><p className="hero-note">No credit score required. No interest.<br/>Fully backed by your <strong>investments.</strong></p></section>
<section className="product-showcase" id="products">{loading?<LoadingState/>:error?<ErrorState message={error}/>:<div className="showcase-columns"><Column title="Featured Products" products={group("Featured")}/><Column title="Best Sellers" products={group("Best Seller")}/><Column title="Best Deals" products={group("Best Deal")}/></div>}</section>
<section className="all-products-section"><div className="section-heading"><div><SectionTag>Marketplace</SectionTag><h2>Find what you need,<span> choose how you pay.</span></h2></div><p>Select a product, choose a variant and pick an EMI plan that works for you.</p></div>{!loading&&!error&&<MarketplaceProductGrid products={products}/>}</section>
<section className="how-section" id="how-it-works"><div className="how-heading"><div><SectionTag>How it Works</SectionTag><h2>Shop using mutual funds<br/>in <span>4 easy steps</span></h2></div><Link to="#" className="button">Check Eligibility <ArrowUpRight size={18}/></Link></div><div className="steps-grid"><Step n="01." title="Choose product & payment plan" text="Select a product, variant and EMI tenure for your favourite device."/><Step n="02." title="Check your eligibility" text="Get your eligibility checked before moving ahead with your purchase."/><Step n="03." title="Select your EMI" text="Review the available plans and select the payment option you prefer."/><Step n="04." title="Proceed with your plan" text="Confirm your selected plan and continue with the purchase flow."/></div></section>
</main><footer className="footer"><div><span className="brand-mark">1Fi</span><p>Shop today. Pay later using mutual funds.</p></div><span>© 2026 1Fi Marketplace</span></footer><FloatingChat/></div>}
